### ISSUE TITLE
Import third party packages on freebsd

### ISSUE THREAD

**Issue by zishucom** [gopherdata/gophernotes#213]
i got flowing same error when i import any thirdpart package on jupyter notebook

error writing file "/projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_nsf_gocode.go": open /projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_nsf_gocode.go: no such file or directory

**Comment by cosmos72** [comment]
Can you copy here the output of `go env` ?
Thanks

**Comment by zishucom** [comment]
dvma@dvma:~ % go env
GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/dvma/.cache/go-build"
GOENV="/home/dvma/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="freebsd"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="freebsd"
GOPATH="/projects/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/freebsd_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build944275286=/tmp/go-build -gno-record-gcc-switches"

**Comment by zishucom** [comment]
> Can you copy here the output of `go env` ?
> 
> Thanks

Hi Thank you

**Comment by cosmos72** [comment]
https://golang.org/doc/go1.14#plugin states that plugin support for freebsd/amd64 was added in Go 1.14

I will update gophernotes and use it for loading third party packages

**Comment by zishucom** [comment]
> https://golang.org/doc/go1.14#plugin states that plugin support for freebsd/amd64 was added in Go 1.14
> 
> 
> 
> I will update gophernotes and use it for loading third party packages 

Thanks! Waiting that

**Comment by cosmos72** [comment]
Support for importing third party packages on freebsd added in commit 4ee426e96bb45036a8c0b480adea5501ba1b464f
Requires Go >= 1.14

**Comment by cosmos72** [comment]
P.S.: `github.com/nsf/gocode` does not seem to be an importable package.

**Comment by zishucom** [comment]
Hi again! These errors still appeared there after I modified the go.mod go.sum and update the gomacro

**Comment by cosmos72** [comment]
In #214 you reported:
> i was upgraded the gomacro. and modified the go.mod and go.sum
>```
>import(
>"github.com/russross/blackfriday/v2"
>)
>
>error writing file "/projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty
>/github_com_russross_blackfriday_v2.go": open /projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_russross_blackfriday_v2.go: no such file or directory

**Comment by zishucom** [comment]
> In #214 you reported that you're still getting the same error:
> 
> > i was upgraded the gomacro. and modified the go.mod and go.sum
> > ```go
> > import(
> > "github.com/russross/blackfriday/v2"
> > )
> > 
> > error writing file "/projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty
> > /github_com_russross_blackfriday_v2.go": open /projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_russross_blackfriday_v2.go: no such file or directory
> > ```
> 
> Why did you "modify the go.mod go.sum and update the gomacro" ?
> 
> The installation instructions start with
> 
> ```shell
> env GO111MODULE=on go get github.com/gopherdata/gophernotes
> ```
> 
> and I thought you were doing that.
> There is no need to modify gophernotes sources manually.

% env GO111MODULE=on go get github.com/gopherdata/gophernotes
go: downloading github.com/gopherdata/gophernotes v0.7.0
go: github.com/gopherdata/gophernotes upgrade => v0.7.0
go: finding module for package github.com/cosmos72/gomacro/base/reflect
go: finding module for package github.com/cosmos72/gomacro/ast2
go: finding module for package github.com/cosmos72/gomacro/base
go: finding module for package github.com/cosmos72/gomacro/imports
go: finding module for package github.com/cosmos72/gomacro/base/paths
go: finding module for package github.com/cosmos72/gomacro/fast
go: finding module for package github.com/cosmos72/gomacro/xreflect
go: found github.com/cosmos72/gomacro/ast2 in github.com/cosmos72/gomacro v0.0.0-20200719111907-b07014b02196
# github.com/gopherdata/gophernotes
/projects/go/pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/display.go:279:9: undefined: "github.com/cosmos72/gomacro/base/reflect".Interface
/projects/go/pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/display.go:279:51: cannot use "reflect".ValueOf(x) (type "reflect".Value) as type xreflect.Value in argument to conv
/projects/go/pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/kernel.go:422:34: cannot use "reflect".ValueOf(receipt.PublishDisplayData) (type "reflect".Value) as type xreflect.Value in argument to displayPlace.Set
/projects/go/pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/kernel.go:425:35: cannot use "reflect".ValueOf(stubDisplay) (type "reflect".Value) as type xreflect.Value in argument to displayPlace.Set
/projects/go/pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/kernel.go:534:11: undefined: "github.com/cosmos72/gomacro/base/reflect".Interface

**Comment by zishucom** [comment]
> In #214 you reported that you're still getting the same error:
> 
> > i was upgraded the gomacro. and modified the go.mod and go.sum
> > ```go
> > import(
> > "github.com/russross/blackfriday/v2"
> > )
> > 
> > error writing file "/projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty
> > /github_com_russross_blackfriday_v2.go": open /projects/go/src/github.com/gopherdata/gophernotes/imports/thirdparty/github_com_russross_blackfriday_v2.go: no such file or directory
> > ```
> 
> Why did you "modify the go.mod go.sum and update the gomacro" ?
> 
> The installation instructions start with
> 
> ```shell
> env GO111MODULE=on go get github.com/gopherdata/gophernotes
> ```
> 
> and I thought you were doing that.
> There is no need to modify gophernotes sources manually.

Hi i reinstalled gophernotes.

cat pkg/mod/github.com/gopherdata/gophernotes@v0.7.0/go.mod

module github.com/gopherdata/gophernotes

go 1.11

require (
        github.com/cosmos72/gomacro v0.0.0-20200226181501-ca599f547e70
        github.com/go-zeromq/zmq4 v0.9.0
        github.com/gofrs/uuid v3.2.0+incompatible
        golang.org/x/sync v0.0.0-20190911185100-cd5d95a43a6e // indirect
        golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
)

why is not 

github.com/cosmos72/gomacro v0.0.0-20200719111907-b07014b02196
???

**Comment by cosmos72** [comment]
Good catch!
Then it means `env GO111MODULE=on go get ...` does not download the latest commit of a module, but only the latest **tagged** commit, i.e. something like "latest released version".

I will release gophernotes 0.7.1 to let `go get` pick it

**Comment by cosmos72** [comment]
[UPDATE] version 0.7.1 released.
Can you please try again
```env GO111MODULE=on go get github.com/gopherdata/gophernotes```
?

**Comment by zishucom** [comment]
Thanks!  But there gets  new error:


import(
    "github.com/360EntSecGroup-Skylar/excelize/"    
)


error loading package "github.com/360EntSecGroup-Skylar/excelize/" metadata: packages.Load() could not find package "github.com/360EntSecGroup-Skylar/excelize/"

---
#ls src/gomacro.imports/github.com/

360EntSecGroup-Skylar

**Comment by cosmos72** [comment]
Try removing the final slash, i.e.
```go
import "github.com/360EntSecGroup-Skylar/excelize"
```
instead of
```go
import "github.com/360EntSecGroup-Skylar/excelize/"  /* note the extra '/' at the end */
```

**Comment by zishucom** [comment]
Thanks for reply!   Yeah I have tried this ! Still get the same error

________________________________
发件人: Massimiliano Ghilardi <notifications@github.com>
发送时间: Wednesday, July 22, 2020 11:11:26 PM
收件人: gopherdata/gophernotes <gophernotes@noreply.github.com>
抄送: zishucom <dvma@live.cn>; Author <author@noreply.github.com>
主题: Re: [gopherdata/gophernotes] Import third party packages on freebsd (#213)


Try removing the final slash, i.e.

import "github.com/360EntSecGroup-Skylar/excelize"

instead of

import "github.com/360EntSecGroup-Skylar/excelize/"  /* note the extra '/' at the end */

―

**Comment by cosmos72** [comment]
That's **really** strange.
Can you to import any package at all? For example,
```go
import "gonum.org/v1/floats"
```

**Comment by zishucom** [comment]
> That's **really** strange.
> 
> Can you import any package at all? For example,
> 
> ```go
> 
> import "gonum.org/v1/gonum/floats"
> 
> ```


Need I install this package? If I don’t need do it . Then I. Get flowing error![image](https://user-images.githubusercontent.com/46121176/88195066-23f7c580-cc72-11ea-8a1a-fad04a10f1cc.jpeg)

**Comment by zishucom** [comment]
> That's **really** strange.
> 
> Can you import any package at all? For example,
> 
> ```go
> 
> import "gonum.org/v1/gonum/floats"
> 
> ```

Same last error here after I installed this package

**Comment by cosmos72** [comment]
Can you post the error (or a screenshot) you get with the following import?
```go
import "gonum.org/v1/gonum/floats"
```
By mistake I wrote "gonum.org/v1/floats" and you tried before I corrected the path

**Comment by cosmos72** [comment]
One more thing: usually there is no need to install packages before importing them.

**Comment by zishucom** [comment]
> One more thing: usually there is no need to install packages before importing them.

![image](https://user-images.githubusercontent.com/46121176/88199762-d54d2a00-cc77-11ea-8155-05934452614d.jpeg)

**Comment by cosmos72** [comment]
ok, then you must have some leftovers from old installations lying around.

You can try with a cleanup:
```shell
go clean
go clean -cache
go clean -modcache
```
then reinstall gophernotes from scratch following the [Linux instructions](https://github.com/gopherdata/gophernotes/#linux) which should work also for FreeBSD.

**Comment by zishucom** [comment]
> ok, then you must have some leftovers from old installations lying around.
> 
> You can try with a cleanup:
> 
> ```shell
> go clean
> go clean -cache
> go clean -modcache
> ```
> 
> then reinstall gophernotes from scratch following the [Linux instructions](https://github.com/gopherdata/gophernotes/#linux) which should work also for FreeBSD.

unforunately........... still not work.... and i did all steps as you say...

**Comment by zishucom** [comment]
> ok, then you must have some leftovers from old installations lying around.
> 
> You can try with a cleanup:
> 
> ```shell
> go clean
> go clean -cache
> go clean -modcache
> ```
> 
> then reinstall gophernotes from scratch following the [Linux instructions](https://github.com/gopherdata/gophernotes/#linux) which should work also for FreeBSD.

thank you verymuch cosmos72 it's working now...
